CC=gcc
make: lcdtest.c
	$(CC) lcdtest.c ../src/gameboy.c ../src/memory.c ../src/cpu.c ../src/registers.c ../src/cartridge.c ../src/flags.c ../src/stack.c ../src/mbc.c ../src/timer.c ../src/bitUtils.c ../src/interrupt.c ../src/lcd.c -o lcdtest -std=c11 -g -Wall
